title: Simranjeet Singh
description: Portfolio, Research Notes, and Projects
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

header_pages:
  - index.md
  - notes.md
  - projects.md
  - about.md
